### ISSUE TITLE
Prefer hidden secondary hosts for backups

### ISSUE THREAD

**Issue by timvaillancourt** [Percona-Lab/mongodb_consistent_backup#11]
It seems the backup tool will pick the replset member which is most in-sync even if there is a hidden secondary.

If it's within safe replication lag limits, we should probably prefer hidden nodes slightly to cause less impact to a live DB setup

**Comment by dbmurphy** [comment]
#23 fixes this

**Comment by timvaillancourt** [comment]
#23 fix validated on 2.4, 2.6 and 3.x.
