### ISSUE TITLE
The code does not act as the warning message

### ISSUE THREAD

**Issue by maulal** [Percona-Lab/mongodb_consistent_backup#153]
To check if the password can be passed by stdin, the program check if the mongodump version is **higher or equal to 3.0.2**, but the warning message talk about **version 3.2.0**.

Test at line: [MongodumpThread.py#L115](https://github.com/Percona-Lab/mongodb_consistent_backup/blob/master/mongodb_consistent_backup/Backup/Mongodump/MongodumpThread.py#L115)
and warning message at line: [MongodumpThread.py#L119](https://github.com/Percona-Lab/mongodb_consistent_backup/blob/master/mongodb_consistent_backup/Backup/Mongodump/MongodumpThread.py#L119)

**Comment by timvaillancourt** [comment]
#156 merged as it's very harmless
