### ISSUE TITLE
S3.py raises a string Exception which is not allowed

### ISSUE THREAD

**Issue by rob256** [Percona-Lab/mongodb_consistent_backup#163]
In `mongodb_consistent_backup/Upload/S3/S3.py`, the `S3` class raises a string exception in its `__init__` method which is currently on line 50. I presume you want this to be:
`raise OperationError("Invalid S3 security key or region detected!")`
rather than just:
`raise "Invalid S3 security key or region detected!"`

**Comment by timvaillancourt** [comment]
Thanks @rob256, this will be in the 1.0.4 release. See the branch '1.0.4' for progress

**Comment by timvaillancourt** [comment]
Fixed and merged into 1.0.4. Closing as this will be released soon.

https://github.com/Percona-Lab/mongodb_consistent_backup/pull/168
