### ISSUE TITLE
slash in collection names, the backup fails

### ISSUE THREAD

**Issue by yoginder** [Percona-Lab/mongodb_consistent_backup#173]
Hi

Thanks for the awesome tool . I am trying to use it via docker.  It fails 

[2017-06-14 21:17:02,893] [INFO] [MongodumpThread-2] [MongodumpThread:wait:92] xxxx-prod-mongo/ip-192-168-160-21.ec2.internal:27000:	Failed: "abc.abc_allows_/api/accounts/list/:userId" contains a path separator '/' and can't be dumped to the filesystem

The same error comes if i try to use mongodump directly, but in mongodump if we give --archive=xxxx.dump, then it succeeds

I dont see any way of passing this config parameter while using the tool here. how can we add more config options like --archive=path_to_dump  , so that this tool can also work

**Comment by yoginder** [comment]
I believe this is same issue as in here,  https://jira.mongodb.org/browse/TOOLS-1163

**Comment by timvaillancourt** [comment]
Hi @yoginder,

I attempted to integrate the 'archive' format of mongodump into the tool early on but it is using a custom mongodump-specific archiving style (not regular tar or zip) that I could not duplicate in the Python code.

Today mongodb_consistent_backup needs to be able to read the captured oplog that outputs from mongodump and I was unable to implement this as I could not get the code to understand the custom archive format. Any suggestions or PRs are appreciated though.

In the future this may be possible as I plan to move 100% of the oplog tailing code into Python and disable oplog capturing in mongodump, meaning the archive format may be possible, but this is not on the roadmap.

**Comment by timvaillancourt** [comment]
Closing this as this is a mongodump error. You'll see --archive= supported in the future under a specific Github issue #. Thanks!
