### ISSUE TITLE
Should error on non-replset/non-cluster systems

### ISSUE THREAD

**Issue by dbmurphy** [Percona-Lab/mongodb_consistent_backup#2]
We assume that if we are not connecting to Mongos, that it should be connecting to a replica set. We should not do this but rather detect if running in stand alone mongod mode, and if so abort warning that it is not possible to have a consistent backup without an oplog ( created when running as a replicaset or shard)

**Comment by timvaillancourt** [comment]
Resolved by 1.0.0 release: https://github.com/Percona-Lab/mongodb_consistent_backup/releases/tag/1.0.0.
