### ISSUE TITLE
AWS EBS Snapshot logic

### ISSUE THREAD

**Issue by atward** [Percona-Lab/mongodb_consistent_backup#220]
I have used a large chunk of the current logic to implement backups using AWS EC2/EBS block level snapshots and am releasing it under the existing Apache Licence.

I'm just raising this issue as an FYI in case it is useful for development/adaptation or inclusion in future releases.
Documentation can be found [here](https://github.com/atward/aws-snapshot/blob/master/README.mongodb.md) with AWS specific logic in pl_mongo.Backup.AwsSnapshot

**Comment by timvaillancourt** [comment]
Duplicate of #19. Please see this issue for updates.
