### ISSUE TITLE
Backup still running even if logs report failure

### ISSUE THREAD

**Issue by Bastian82** [Percona-Lab/mongodb_consistent_backup#245]
We suffering errors described here #165 
In log we can read that mongodb-consistent-backup failed and it is stoping mongodump threads:
[https://pastebin.com/9vBvVXvG](https://pastebin.com/9vBvVXvG)

but processes is still running and mongodump still dumping data to the backup directories:
[https://pastebin.com/e7eLz9vu](https://pastebin.com/e7eLz9vu)

**Comment by timvaillancourt** [comment]
Hi @Bastian82, as you allude this is a duplicate of #165. I will consolidate the issues.
