### ISSUE TITLE
Sharding is not enabled on collection after backing up

### ISSUE THREAD

**Issue by cryax** [Percona-Lab/mongodb_consistent_backup#256]
Sharding is not enabled on collection after backing up

**Comment by timvaillancourt** [comment]
Hi @cryax. The mongodb_consistent_backup tool does not change the state of collections sharding, it only calls Mongodump after performing read-only queries.

In fact, if the authentication user is setup correctly (see README.md section) mongodb_consistent_backup does not have access to the commands to change collections if it tried to.

Closing this issue for now. Please test and re-open with logs, errors or steps/versions to reproduce this issue.
