### ISSUE TITLE
mongorestore

### ISSUE THREAD

**Issue by yidazhi** [Percona-Lab/mongodb_consistent_backup#261]
db.a.drop()
mongorestore 

 - E11000 duplicate key error collection: config.cache.collections index: _id_ dup key: { : "myTest.a" }
  - E11000 duplicate key error collection: config.cache.collections index: _id_ dup key: { : "config.system.sessions" }
  - E11000 duplicate key error collection: admin.system.keys index: _id_ dup key: { : 6552736384082247681 }
  - E11000 duplicate key error collection: admin.system.keys index: _id_ dup key: { : 6552736384082247682 }
  - E11000 duplicate key error collection: config.cache.chunks.myTest.a index: _id_ dup key: { : { _id: MinKey } }
  - E11000 duplicate key error collection: config.cache.chunks.myTest.a index: _id_ dup key: { : { _id: 0 } }

**Comment by timvaillancourt** [comment]
Hi @yidazhi, please add the '--drop' flag to mongorestore to avoid this problem.

**Comment by timvaillancourt** [comment]
Closing due to no update, please reopen if there is an update.
