### ISSUE TITLE
mongodb-consistent-backup vs. Ops Manager backup to RS documentation/blog posting

### ISSUE THREAD

**Issue by GETandSELECT** [Percona-Lab/mongodb_consistent_backup#47]
I wish to read how mongodb-consistent-backup compares to commercial Ops Manager / Cloud Manager backup feature. Please write some lines.

**Comment by dbmurphy** [comment]
Hi @GETandSELECT,

This will become clearer and documented when this tool becomes an official tool and is no longer in labs.  Currently, this tool is using logical backups and not the snapshot modes you would find in OpsManager. What it does do is bridge the gap from mongodump which is not shard-safe as it will only read from primaries and  is not cluster aware. That is this tool adds oplog capture and aligns it across all shards so all shard will capture oplog for until all dumps are done. 

Moving forward we are working toward things like EBS and LVM snapshots but this not current in the system. 

This might also help:
https://www.percona.com/blog/2016/07/25/mongodb-consistent-backups/

Does this help?
