### ISSUE TITLE
Add other notification methods

### ISSUE THREAD

**Issue by TimBanks** [Percona-Lab/mongodb_consistent_backup#49]
Having push notification methods for pagerduty, email, prometheus, etc would add to the versatility of this feature.

**Comment by dbmurphy** [comment]
@TimBanks  You might want to look at the  MDB_1.0 branch as we are doing more of the modular work to make this easier for people to contribute new methods.  The modular notifications should merged today, but we need to do some  config file magic before it  will be buildable

**Comment by timvaillancourt** [comment]
Created #243 and #244 for PagerDuty and Email.

Please open specific issues for any other requests for methods, this request is too large/vague.
