### ISSUE TITLE
max_lag_secs should be a tunable parameter

### ISSUE THREAD

**Issue by TimBanks** [Percona-Lab/mongodb_consistent_backup#52]
The max_lag_secs value used to determine how lagged a secondary can be in order to proceed with a backup should be a tunable/user defined value. This will allow users to proceed with a backup even with what is a reasonable amount of lag for their environment.

**Comment by timvaillancourt** [comment]
Hi Tim,

This can be set with the -m/--maxlag flag (or 'max_repl_lag_secs' in the yml config) with the number of max seconds of lag.

```
  -m MAX_REPL_LAG_SECS, --maxlag=MAX_REPL_LAG_SECS
                        Maximum MongoDB replication secondary slave drift in
                        seconds (default: 5)
```

A heads up that the YAML config structure will move to a more-organised, nested structure in an update soon.

**Comment by timvaillancourt** [comment]
Closing this issue, please reopen if you have any problems!
