### ISSUE TITLE
Should replication lag be calculated from heartbeat metrics?

### ISSUE THREAD

**Issue by genuss** [Percona-Lab/mongodb_consistent_backup#53]
Currently I use mongodb_consistent_backup as a backup tool for my config-server replica set. In this case updates are very rare. The tool calculates lag using last oplog operation time. In my case this often causes false-positive results of `too-high replication lag`. Will it be more consious to use [lastHeartBeat*](https://docs.mongodb.com/manual/reference/command/replSetGetStatus/#replSetGetStatus.members[n].lastHeartbeat) metrics or am I missing something here?
As an example please see attached metrics from one of my secondary replica:
![image](https://cloud.githubusercontent.com/assets/3119969/19685578/0d80ceb4-9ac6-11e6-924e-83ecba908be3.png)
Note the oplog lag goes up to 10 seconds although heartBeat doesn't exceed 2 seconds (my heartbeatInterval)

**Comment by timvaillancourt** [comment]
Interesting question @genuss, I never thought of that.

Are you proposing we subtract the time since lastHeartBeat from the seconds of lag? That seems reasonable to me.

**Comment by genuss** [comment]
Yes, that's indeed what I'm proposing.

**Comment by timvaillancourt** [comment]
This logic was adopted in 1.0.0. We now consider the "operational lag" of heartbeats in lag calculations.

https://github.com/Percona-Lab/mongodb_consistent_backup/releases/tag/1.0.0.

**Comment by genuss** [comment]
Very nice! Thank you!
