### ISSUE TITLE
1.2.0 Milestone: Support SSL connections

### ISSUE THREAD

**Issue by TimJones** [Percona-Lab/mongodb_consistent_backup#60]
I don't see any way of connection to a MongoDB instance via SSL, it should be added if not or documented if available.

**Comment by dbmurphy** [comment]
I will need to check with Tim, I am not near my computer right now but I thought this had been added if not it's a bug. We are in the middle of a major refactor so maybe it's in the new code but not the old

**Comment by TimJones** [comment]
I am running from the master branch, and in [MongoBackup/Common/DB.py#L24-L28](https://github.com/Percona-Lab/mongodb_consistent_backup/blob/master/MongoBackup/Common/DB.py#L24-L28) there is no support of the PyMongo SSL options.
